baseURL: https://tokyodiaries.com
languageCode: en-us
title: "Tokyo Diaries - My Life Abroad" 
googleAnalytics: G-JH38S1T3SL
theme: ["PaperMod"]

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.

  defaultTheme: auto
  # disableThemeToggle: true
  # ShowShareButtons: false
  ShowReadingTime: true
  disableSpecial1stPost: true
  # displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  # ShowCodeCopyButtons: true
  # ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  # ShowPageNums: true
  # ShowToc: false
  # comments: false

  homeInfoParams:
    Title: Welcome to Tokyo Diaries
    Content: I moved from Hawai ªi to Japan in 2016 to attend university and have been here ever since. I had originally planned to move back home after I graduated, but I kept finding reasons to extend my stay. Having recently left my corporate role, I'm taking this opportunity to explore my next adventure and I'd love to share insights from my time in Japan with anyone interested. As I navigate this new chapter, I want to reflect on the experiences that have shaped my journey in Japan. 

    
outputs:
  home:
    - HTML
    - RSS
    - JSON